version: '3.8'

services:

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  authz:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    env_file:
      - .env 
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data:
